# Generated by Django 5.2.3 on 2025-07-07 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='description',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='logo',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_banners/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='RestaurantGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sat', 'شنبه'), ('sun', 'یک\u200cشنبه'), ('mon', 'دو\u200cشنبه'), ('tue', 'سه\u200cشنبه'), ('wed', 'چهار\u200cشنبه'), ('thu', 'پنج\u200cشنبه'), ('fri', 'جمعه')], max_length=3)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('restaurant', 'day')},
            },
        ),
    ]
