# Generated by Django 5.2.3 on 2025-07-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_description_restaurant_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='eng_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/logos/', verbose_name='لوگوی رستوران'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار رستوران'),
        ),
    ]
