# Generated by Django 5.2.3 on 2025-07-09 12:26

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_tablecall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_banners/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='eng_name',
            field=models.CharField(blank=True, default='restaurant<django.db.models.fields.related.OneToOneField>', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/logos/<django.db.models.fields.CharField>/', verbose_name='لوگوی رستوران'),
        ),
        migrations.AlterField(
            model_name='restaurantgallery',
            name='image',
            field=models.ImageField(upload_to='restaurant_gallery/None/'),
        ),
        migrations.AlterField(
            model_name='restaurantvideo',
            name='video',
            field=models.FileField(upload_to='restaurant/videos/None/'),
        ),
    ]
