# Generated by Django 5.2.3 on 2025-07-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'آقا'), ('female', 'خانم'), ('other', 'سایر...')], max_length=10, null=True),
        ),
    ]
