# Generated by Django 5.2.3 on 2025-07-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_slug_alter_blogcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reading_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_categories/covers/'),
        ),
    ]
