# Generated by Django 5.2.3 on 2025-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده'), ('delivered', 'تحویل داده شده')], default='pending', max_length=20),
        ),
    ]
