# Generated by Django 5.2.3 on 2025-07-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_loyalty_added',
            field=models.BooleanField(default=False),
        ),
    ]
