# Generated by Django 5.2.3 on 2025-07-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order__loyalty_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_loyalty_added',
        ),
    ]
